### ISSUE TITLE
22-04-15-FRI

### ISSUE THREAD

**Issue by snaag** [snaag/TIL#8]

**Comment by snaag** [comment]
```css
:host ::ng-deep .my-tooltip-style {
   top: -10px !important;
}
```
